-- Landing page CMS keys (editable via /admin/landing-page)
INSERT INTO `cms_content` (`key_name`, `section`, `content_type`, `content_value`, `sort_order`) VALUES
('hero_badge', 'hero', 'text', 'Now Serving 2,000+ Farmers in Tanzania', 1),
('hero_title', 'hero', 'text', 'Bridging technology and the field.', 2),
('hero_subtitle', 'hero', 'text', 'AI-powered agricultural advisory system. Connecting local farmers with expert guidance, real-time weather alerts, and precision crop scheduling via SMS and Web.', 3),
('hero_image', 'hero', 'image', '/assets/images/hero.png', 4),
('hero_card_weather_label', 'hero', 'text', 'Weather Alert', 5),
('hero_card_weather_text', 'hero', 'text', 'Light Rain Today', 6),
('hero_card_ai_label', 'hero', 'text', 'AI Advisor', 7),
('hero_card_ai_text', 'hero', 'text', 'Mbolea iwekwe sasa.', 8),
('features_section_label', 'features', 'text', 'How It Works', 10),
('features_title', 'features', 'text', 'Everything a modern rural farmer needs to succeed.', 11),
('feature1_title', 'features', 'text', 'AI Soil & Crop Analysis', 12),
('feature1_desc', 'features', 'text', 'Get instant answers via SMS or Web about crop diseases, soil health, and fertilizer schedules powered by localized AI models trained on Tanzanian data.', 13),
('feature2_title', 'features', 'text', 'Precision Weather', 14),
('feature2_desc', 'features', 'text', 'Ward-level weather forecasting and alerts. Know exactly when to plant, irrigate, or harvest based on micro-climate data delivered straight to your phone.', 15),
('feature3_title', 'features', 'text', 'Expert Officer Visits', 16),
('feature3_desc', 'features', 'text', 'If AI cannot answer your question, it is instantly escalated to your local Ward Agricultural Officer who can schedule an in-person farm visit.', 17),
('impact_title', 'impact', 'text', 'Measurable Impact Across The Nation', 20),
('impact_subtitle', 'impact', 'text', 'Since deploying Agri-Advisory in pilot districts, we have seen significant improvements in crop yields and reduction in pest-related losses.', 21),
('impact_stat1_value', 'impact', 'text', '42%', 22),
('impact_stat1_label', 'impact', 'text', 'Increase in Yield', 23),
('impact_stat2_value', 'impact', 'text', '12k+', 24),
('impact_stat2_label', 'impact', 'text', 'Active Farmers', 25),
('impact_stat3_value', 'impact', 'text', '150k', 26),
('impact_stat3_label', 'impact', 'text', 'AI Queries Answered', 27),
('impact_stat4_value', 'impact', 'text', '31', 28),
('impact_stat4_label', 'impact', 'text', 'Regions Covered', 29),
('impact_harvest_title', 'impact', 'text', 'Recent Harvest Data', 30),
('impact_harvest_badge', 'impact', 'text', 'Live Sync', 31),
('harvest_row1_region', 'impact', 'text', 'Morogoro', 32),
('harvest_row1_crop', 'impact', 'text', 'Maize', 33),
('harvest_row1_yield', 'impact', 'text', '24 bags/acre', 34),
('harvest_row2_region', 'impact', 'text', 'Kigoma', 35),
('harvest_row2_crop', 'impact', 'text', 'Beans', 36),
('harvest_row2_yield', 'impact', 'text', '8 bags/acre', 37),
('harvest_row3_region', 'impact', 'text', 'Dodoma', 38),
('harvest_row3_crop', 'impact', 'text', 'Sorghum', 39),
('harvest_row3_yield', 'impact', 'text', '12 bags/acre', 40),
('harvest_row4_region', 'impact', 'text', 'Mbeya', 41),
('harvest_row4_crop', 'impact', 'text', 'Rice', 42),
('harvest_row4_yield', 'impact', 'text', '30 bags/acre', 43),
('cta_title', 'cta', 'text', 'Ready to transform your farming?', 50),
('cta_subtitle', 'cta', 'text', 'Join thousands of farmers making data-driven decisions every day. No smartphone required — our core services work entirely via standard SMS.', 51),
('cta_button', 'cta', 'text', 'Create Free Account', 52),
('footer_brand', 'footer', 'text', 'Agri-Advisory', 60),
('footer_copyright', 'footer', 'text', '© 2024 Agri-Advisory System. All rights reserved.', 61),
('nav_features', 'footer', 'text', 'Features', 62),
('nav_impact', 'footer', 'text', 'Impact', 63),
('nav_pricing', 'footer', 'text', 'Pricing', 64)
ON DUPLICATE KEY UPDATE `section` = VALUES(`section`), `content_type` = VALUES(`content_type`), `sort_order` = VALUES(`sort_order`);
